name: cy_cube
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  camera: ^0.8.0
  rename: ^3.0.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  image: ^3.0.2
  socket_io_client: ^2.0.3+1
  linear_progress_bar: ^1.1.2
  lottie: ^3.1.2
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  msh_checkbox: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/